@startuml
hide empty description

[*] --> Ausgeschaltet
Ausgeschaltet  -right-> Reparatur : <!BW1;BW2>
Ausgeschaltet  -down-> Automatik : <BW1;BW2>
Ausgeschaltet  -down-> Handbetrieb : <BW1;!BW2>


Ausgeschaltet  <- Reparatur : <!BW1;!BW2>
Ausgeschaltet  <- Handbetrieb : <!BW1;!BW2>
Ausgeschaltet  <- Automatik : <!BW1;!BW2>

Reparatur --> Automatik : <BW1;BW2>
Reparatur -left-> Handbetrieb : <BW1;!BW2>


Reparatur <- Automatik : <!BW1;BW2>
Reparatur <- Handbetrieb : <!BW1;BW2>

Automatik --> Handbetrieb : <BW1;!BW2>

Automatik <-- Handbetrieb : <BW1;BW2>

@enduml