@startuml
hide empty description

[*] --> Ausgeschsltet
Ausgeschsltet  -down-> Reperatur : <!BW1;BW2>
Ausgeschsltet  -down-> Automatik : <BW1;BW2>
Ausgeschsltet  -down-> Handbetrieb : <BW1;!BW2>


Ausgeschsltet  <- Reperatur : <!BW1;!BW2>
Ausgeschsltet  <- Handbetrieb : <!BW1;!BW2>
Ausgeschsltet  <- Automatik : <!BW1;!BW2>

Reperatur --> Automatik : <BW1;BW2>
Reperatur -left-> Handbetrieb : <BW1;!BW2>


Reperatur <- Automatik : <!BW1;BW2>
Reperatur <- Handbetrieb : <!BW1;BW2>

Automatik --> Handbetrieb : <BW1;!BW2>

Automatik <-- Handbetrieb : <BW1;BW2>

@enduml